language: c
script: asdf plugin-test eksctl $TRAVIS_BUILD_DIR 'eksctl version'
before_script:
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
os:
  - linux
  - osx
env:
  global:
    secure: J2ilvnJAhEOJYpfbmFSw13/IVz/0B0zpKjd1+yg2gC+kNtQGLRRyjrOtCijl2UvuM94usv8XKJh+jN4igS2uc9LrXKkyTo2CG0KVepsVfUBEb63kLZqHtxZ2VvxFLRnSm2OKwF0by1RK+MIKcUK6bgc88+QN1uQ4KW2emm1p0YA4noon2YREXf580FZ3tKT2v5Y5gDroBad6/v0CxnTW6ewGjUlm8T+nwWuddo0osl6f1YE/AgOMWl7QOJ8w6c0rFPpR+nCNWZoFtvpPdyMvYmObrA21QuyfDtmTUvuOA2vI9lcztW9SXTlir8A6l5rzlpH7P2JRtHPO3vcaTWQgEfPPYSSSF/n8F87ug2BDxO91LeBolkX0cW5lkjQhOeXMCF2td/PhwKq+hRJWKqAaMLrmoY+Wkf/Yp+32nXc1fRRCgp3lzbi66TxVfOyElGOj3Qya7yWhrYJRgVYKGxuJLlal8zjR0G3KZlxQogot/QmBScXkhA6wef3WaFGrQ+tJY6XcXgTuCHhuvu9k0UqapUi4h4yXngoHGQM6lf06fz23uey2qya6yoMg/dYncfdAkMWuBrG9SJDu7q7NqCwKE4Dy6WtFMP4y7HUynoBdhBLSOcjqS5QiYcvXS3oC1xuVklO5MZ13cVPC2FYo/rKI4r4SbpL9AOuOUvOS/bGx3GA=
