name: Main workflow

on:
  push:
    paths-ignore:
      - "**.md"
      - ".all-contributorsrc"
  pull_request:
    paths-ignore:
      - "**.md"
      - ".all-contributorsrc"
  schedule:
    - cron: "0 0 * * 5"

jobs:
  plugin_test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: eksctl latest
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: eksctl version
      - name: eksctl <= 0.63.0
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: asdf-vm/actions/plugin-test@v1
        with:
          version: 0.63.0
          command: eksctl version
